#!/usr/bin/python
# -*- coding: utf-8 -*-
# This and all files in the Larm package is Copyright 2007 Johannes Burström,
# <johannes@ljud.org>, except where otherwise noted.

# This file is part of Larm.

# Larm is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Foobar is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Larm.  If not, see <http://www.gnu.org/licenses/>.


import sys, os

cmd = "".join(["nice -n15 ", sys.path[0], "/main.py"])
os.system(cmd)
